### PR TITLE
Refactor to Typescript

### LINKED ISSUE #4: Typescript support
This issue is to track progress towards moving to Typescript. See #3 for reasoning as to why the move is necessary.

### PR DESCRIPTION
**Pull request by MaddyUnderStars**
Resolves #4 as per request in #3

### CODE REVIEW

**Comment by MaddyUnderStars** [comment]
I am unhappy with the current typing of `string`, which is forced due to a7ed0dd561c76ab256b1dee6043b034c28b7d602. Do you think this is acceptable?

**Comment by skyrina** [comment]
> which is forced due to a7ed0dd

Thank you for bringing this to my attention. Upon closer inspection,  I agree that the current typing of the string is not acceptable and I understand that you are unhappy with the forced typing as a result.

I recommend that we revert the commit in question and explore alternative solutions for addressing the issue at hand. Please let me know if you agree with this course of action, and we can proceed accordingly.

Thank you for your patience and understanding.

**Comment by MaddyUnderStars** [comment]
> I recommend that we revert the commit in question

Rather than revert, which would unnecessarily introduce an additional commit to our history, a fix has been pushed to address this.

**Review by skyrina — APPROVED** [review]
Thank you for submitting this pull request to fix the typings. I have reviewed the changes and am pleased to approve of them.

The updated typings look well-structured and accurate, and I appreciate the effort you have put into ensuring that the code is properly typed. These changes will improve the reliability and maintainability of the codebase, and I believe they will be a valuable addition to the project.

Thank you for your contributions and for working to improve the codebase. I look forward to seeing the results of these changes in action.

**Pull request merged**
